os:
  - linux
  - osx

language: csharp

env:
  - CONFIGURATION=Release FLAVOUR=release

mono:
  - latest

matrix:
  allow_failures:
    - os: osx

solution: IronPython.sln

before_install:
  - curl https://api.nuget.org/downloads/nuget.exe -o nuget.exe
  - mono nuget.exe install NUnit
  - mono nuget.exe install NUnitLite

script:
  - git submodule update --init --recursive
  - make $FLAVOUR
  - pushd bin/$CONFIGURATION
  - mono ./IronPythonTest.exe --result:all-result.xml

notifications:
  email:
    recipients:
      - slide.o.mix@gmail.com
      - ticotimo@gmail.com
    on_success: always # default: change
    #on_failure: [always|never|change] # default: always

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f04e10a7af4b181c18c0
